# Python Exploratory Data Analysis

**Based On Pharmacy Dataset On Kaggle**

### Phase 1

#### Importing All required Libraries

In [3]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [6]:
df = pd.read_excel('Pharmacy_data.xlsx')
df.head()

,SalesID,DateKey,PharmacyID,ProductID,UnitsSold,RevenueEUR,CostEUR,MarginEUR,PromoFlag
0,S0000001,20240101,PH0002,PR0099,5,128.08,87.55,40.53,No
1,S0000002,20240101,PH0004,PR0156,4,51.89,34.32,17.57,No
2,S0000003,20240101,PH0007,PR0004,20,317.73,199.53,118.20,No
3,S0000004,20240101,PH0009,PR0075,6,90.34,67.49,22.85,No
4,S0000005,20240101,PH0010,PR0154,2,160.21,124.99,35.22,Yes

## Phase 2

#### Initial Exploration

In [10]:
df.size

559251

In [12]:
df.shape

(62139, 9)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62139 entries, 0 to 62138
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SalesID     62139 non-null  object
 1   DateKey     62139 non-null  int64
 2   PharmacyID  62139 non-null  object
 3   ProductID   62139 non-null  object
 4   UnitsSold   62139 non-null  int64
 5   RevenueEUR  62139 non-null  float64
 6   CostEUR     62139 non-null  float64
 7   MarginEUR   62139 non-null  float64
 8   PromoFlag   62139 non-null  object
dtypes: float64(3), int64(2), object(4)
memory usage: 4.3+ MB

In [16]:
df.tail(10)

,SalesID,DateKey,PharmacyID,ProductID,UnitsSold,RevenueEUR,CostEUR,MarginEUR,PromoFlag
62129,S0062130,20251231,PH0110,PR0177,4,42.64,31.38,11.26,No
62130,S0062131,20251231,PH0110,PR0114,9,251.07,149.72,101.35,No
62131,S0062132,20251231,PH0111,PR0186,9,177.66,120.81,56.85,No
62132,S0062133,20251231,PH0112,PR0135,4,89.25,60.10,29.15,No
62133,S0062134,20251231,PH0115,PR0126,5,20.49,13.55,6.94,No
62134,S0062135,20251231,PH0117,PR0101,2,159.56,118.31,41.25,Yes
62135,S0062136,20251231,PH0118,PR0125,5,136.15,92.63,43.52,No
62136,S0062137,20251231,PH0120,PR0183,4,43.51,30.22,13.29,No
62137,S0062138,20251231,PH0120,PR0151,11,129.27,83.37,45.90,No
62138,S0062139,20251231,PH0120,PR0145,3,227.54,177.03,50.51,No

## Phase 3

### Statistical Summary

In [20]:
#Statistical Summary OF The Dataset
df.describe()

            DateKey     UnitsSold    RevenueEUR       CostEUR     MarginEUR
count  6.213900e+04  62139.000000  62139.000000  62139.000000  62139.000000
mean   2.024579e+07      7.174126    138.946190     99.982881     38.963309
std    5.014700e+03      4.873395    124.574712     93.611370     33.972445
min    2.024010e+07      1.000000      1.610000      1.100000      0.440000
25%    2.024071e+07      3.000000     55.250000     39.330000     15.140000
50%    2.025011e+07      6.000000    102.750000     72.220000     28.990000
75%    2.025071e+07     10.000000    181.350000    128.680000     51.990000
max    2.025123e+07     25.000000   1036.280000    834.420000    295.310000

## Phase 4

### Data Cleaning

In [21]:
#Check for missing fields
df.isna().sum()

SalesID       0
DateKey       0
PharmacyID    0
ProductID     0
UnitsSold     0
RevenueEUR    0
CostEUR       0
MarginEUR     0
PromoFlag     0
dtype: int64

In [22]:
df.shape

(62139, 9)

In [26]:
# Drop the duplicated value
df.drop_duplicates()

,SalesID,DateKey,PharmacyID,ProductID,UnitsSold,RevenueEUR,CostEUR,MarginEUR,PromoFlag
0,S0000001,20240101,PH0002,PR0099,5,128.08,87.55,40.53,No
1,S0000002,20240101,PH0004,PR0156,4,51.89,34.32,17.57,No
2,S0000003,20240101,PH0007,PR0004,20,317.73,199.53,118.20,No
3,S0000004,20240101,PH0009,PR0075,6,90.34,67.49,22.85,No
4,S0000005,20240101,PH0010,PR0154,2,160.21,124.99,35.22,Yes
...,...,...,...,...,...,...,...,...,...
62134,S0062135,20251231,PH0117,PR0101,2,159.56,118.31,41.25,Yes
62135,S0062136,20251231,PH0118,PR0125,5,136.15,92.63,43.52,No
62136,S0062137,20251231,PH0120,PR0183,4,43.51,30.22,13.29,No
62137,S0062138,20251231,PH0120,PR0151,11,129.27,83.37,45.90,No
62138,S0062139,20251231,PH0120,PR0145,3,227.54,177.03,50.51,No

In [29]:
df.columns

Index(['SalesID', 'DateKey', 'PharmacyID', 'ProductID', 'UnitsSold',
       'RevenueEUR', 'CostEUR', 'MarginEUR', 'PromoFlag'],
      dtype='object')

## Phase 5

### Dimensional Modeling

In [31]:
df.head()

,SalesID,DateKey,PharmacyID,ProductID,UnitsSold,RevenueEUR,CostEUR,MarginEUR,PromoFlag
0,S0000001,20240101,PH0002,PR0099,5,128.08,87.55,40.53,No
1,S0000002,20240101,PH0004,PR0156,4,51.89,34.32,17.57,No
2,S0000003,20240101,PH0007,PR0004,20,317.73,199.53,118.20,No
3,S0000004,20240101,PH0009,PR0075,6,90.34,67.49,22.85,No
4,S0000005,20240101,PH0010,PR0154,2,160.21,124.99,35.22,Yes

In [32]:
# CREATE DIM_PRODUCT
dim_product = df[['ProductID']].drop_duplicates().sort_values('ProductID').reset_index(drop=True)

In [34]:
dim_product

    ProductID
0      PR0001
1      PR0002
2      PR0003
3      PR0004
4      PR0005
..        ...
215    PR0216
216    PR0217
217    PR0218
218    PR0219
219    PR0220

[220 rows x 1 columns]

In [35]:
# CREATE DIM_DATE 
dim_date = df[['DateKey']].drop_duplicates().reset_index(drop=True)

In [36]:
dim_date

      DateKey
0    20240101
1    20240102
2    20240103
3    20240104
4    20240105
..        ...
726  20251227
727  20251228
728  20251229
729  20251230
730  20251231

[731 rows x 1 columns]

In [41]:
# Force the column to be a string first, then convert using the exact YYYYMMDD structure
dim_date['Date'] = pd.to_datetime(dim_date['DateKey'].astype(str), format='%Y%m%d', errors='coerce')

dim_date['DayName'] = dim_date['Date'].dt.day_name()
dim_date['MonthName'] = dim_date['Date'].dt.month_name()
dim_date['Quarter'] = 'Q' + dim_date['Date'].dt.quarter.astype(str)
dim_date['Year'] = dim_date['Date'].dt.year

In [42]:
dim_date

      DateKey       Date    DayName MonthName Quarter  Year
0    20240101 2024-01-01     Monday   January      Q1  2024
1    20240102 2024-01-02    Tuesday   January      Q1  2024
2    20240103 2024-01-03  Wednesday   January      Q1  2024
3    20240104 2024-01-04   Thursday   January      Q1  2024
4    20240105 2024-01-05     Friday   January      Q1  2024
..        ...        ...        ...       ...     ...   ...
726  20251227 2025-12-27   Saturday  December      Q4  2025
727  20251228 2025-12-28     Sunday  December      Q4  2025
728  20251229 2025-12-29     Monday  December      Q4  2025
729  20251230 2025-12-30    Tuesday  December      Q4  2025
730  20251231 2025-12-31  Wednesday  December      Q4  2025

[731 rows x 6 columns]

In [43]:
# CREATE FACT_SALES
fact_sales = df[['SalesID', 'DateKey', 'PharmacyID', 'ProductID', 'UnitsSold', 'RevenueEUR', 'CostEUR', 'MarginEUR', 'PromoFlag']]

In [44]:
fact_sales

,SalesID,DateKey,PharmacyID,ProductID,UnitsSold,RevenueEUR,CostEUR,MarginEUR,PromoFlag
0,S0000001,20240101,PH0002,PR0099,5,128.08,87.55,40.53,No
1,S0000002,20240101,PH0004,PR0156,4,51.89,34.32,17.57,No
2,S0000003,20240101,PH0007,PR0004,20,317.73,199.53,118.20,No
3,S0000004,20240101,PH0009,PR0075,6,90.34,67.49,22.85,No
4,S0000005,20240101,PH0010,PR0154,2,160.21,124.99,35.22,Yes
...,...,...,...,...,...,...,...,...,...
62134,S0062135,20251231,PH0117,PR0101,2,159.56,118.31,41.25,Yes
62135,S0062136,20251231,PH0118,PR0125,5,136.15,92.63,43.52,No
62136,S0062137,20251231,PH0120,PR0183,4,43.51,30.22,13.29,No
62137,S0062138,20251231,PH0120,PR0151,11,129.27,83.37,45.90,No
62138,S0062139,20251231,PH0120,PR0145,3,227.54,177.03,50.51,No

In [45]:
#  Export files as CSV file
dim_product.to_csv('DimProduct.csv', index=False)
dim_date.to_csv('DimDate.csv', index=False)
fact_sales.to_csv('FactSales.csv', index=False)